#!/bin/bash
# Quick commands to fix and verify GPT-4 formula flow

echo "========================================="
echo "GPT-4 FORMULA FIX - QUICK COMMANDS"
echo "========================================="
echo ""
echo "Run these commands in order:"
echo ""
echo "1. Check current status:"
echo "   python check_status.py"
echo ""
echo "2. Apply the missing preservation fix:"
echo "   python fix_preservation.py"
echo ""
echo "3. Verify all fixes:"
echo "   python check_status.py"
echo ""
echo "4. Trace the calculation flow:"
echo "   python trace_flow.py"
echo ""
echo "5. Test the flow independently:"
echo "   python test_formula_flow.py"
echo ""
echo "========================================="
echo "If automated fixes don't work:"
echo "   python manual_preservation_fix.py"
echo "   (Shows exact manual instructions)"
echo "========================================="
